# fly.toml app configuration file generated for chatapp-project-misty-cherry-4184 on 2025-04-16T08:58:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chatapp-swfkkg"
console_command = "/code/manage.py shell"
deploy = { }
primary_region = "bos"

[env]
PORT = "8000"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_000
min_machines_running = 0
processes = [ "app" ]

[[statics]]
guest_path = "/code/static"
tigris_bucket = ""
url_prefix = "/static/"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"

