# Generated by Django 5.2 on 2025-04-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatUser',
        ),
    ]
